name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Static Check
        run: |
          if ! command -v staticcheck &> /dev/null; then
            go install honnef.co/go/tools/cmd/staticcheck@latest
          fi
          staticcheck ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install LLVM
        env:
          LLVM_VERSION: 15.0.7
        run: |
          ID="$(docker create --name llvm ghcr.io/vietanhduong/wbpf-llvm:${LLVM_VERSION})"
          sudo docker cp "$ID:/usr/local/bin/clang*" /usr/local/bin
          docker rm $ID
          ls -lah /usr/local/bin/clang*

      - name: Run Test
        run: |
          sudo apt-get install -y make
          TEST_CC=$(which clang) go test ./... -v -exec=sudo -count=1

      - name: Build examples
        run: make -C examples CC=$(which clang) BUILD_BPF=1 build-all
