name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Static Check
        run: |
          if ! command -v staticcheck &> /dev/null; then
            go install honnef.co/go/tools/cmd/staticcheck@latest
          fi
          staticcheck ./...

      - name: Run Test
        run: |
          sudo apt-get install -y clang-15 llvm-15 make
          TEST_CC=$(which clang) go test ./... -v -exec=sudo -count=1

      - name: Build examples
        run: make -C examples CC=$(which clang) BUILD_BPF=1 build-all
